#!/bin/bash
# =============================================================================
# OpenClaw GCP Deployment - Startup Script
# =============================================================================
# This script is executed on first boot to:
# 1. Install Docker and Docker Compose
# 2. Install and configure Tailscale
# 3. Clone and configure OpenClaw
# 4. Start the OpenClaw Gateway
# =============================================================================

set -euo pipefail

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a /var/log/openclaw-startup.log
}

log "=========================================="
log "Starting OpenClaw GCP Deployment"
log "=========================================="

# -----------------------------------------------------------------------------
# Configuration from Terraform
# -----------------------------------------------------------------------------

TAILSCALE_AUTH_KEY="${tailscale_auth_key}"
TAILSCALE_HOSTNAME="${tailscale_hostname}"
TAILSCALE_ADVERTISE_TAGS="${tailscale_advertise_tags}"
TAILSCALE_SERVE_MODE="${tailscale_serve_mode}"
OPENCLAW_GATEWAY_PORT="${openclaw_gateway_port}"
OPENCLAW_GATEWAY_TOKEN="${openclaw_gateway_token}"
OPENCLAW_GATEWAY_PASSWORD="${openclaw_gateway_password}"
ANTHROPIC_API_KEY="${anthropic_api_key}"
OPENAI_API_KEY="${openai_api_key}"
TELEGRAM_BOT_TOKEN="${telegram_bot_token}"
DISCORD_BOT_TOKEN="${discord_bot_token}"
SLACK_BOT_TOKEN="${slack_bot_token}"
SLACK_APP_TOKEN="${slack_app_token}"

# Deployment paths
OPENCLAW_DIR="/opt/openclaw"
OPENCLAW_STATE_DIR="/home/openclaw/.openclaw"
OPENCLAW_WORKSPACE_DIR="/home/openclaw/.openclaw/workspace"

# -----------------------------------------------------------------------------
# System Updates
# -----------------------------------------------------------------------------

log "Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# Install required packages
log "Installing required packages..."
apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git \
    jq \
    unzip \
    htop \
    vim

# -----------------------------------------------------------------------------
# Create OpenClaw User
# -----------------------------------------------------------------------------

log "Creating openclaw user..."
if ! id "openclaw" &>/dev/null; then
    useradd -m -s /bin/bash openclaw
fi

# Create directories
mkdir -p "$OPENCLAW_DIR"
mkdir -p "$OPENCLAW_STATE_DIR"
mkdir -p "$OPENCLAW_WORKSPACE_DIR"
mkdir -p "$OPENCLAW_STATE_DIR/credentials"
mkdir -p "$OPENCLAW_STATE_DIR/agents"

# Set ownership
chown -R openclaw:openclaw /home/openclaw
chown -R openclaw:openclaw "$OPENCLAW_DIR"

# -----------------------------------------------------------------------------
# Install Docker
# -----------------------------------------------------------------------------

log "Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    
    # Add openclaw user to docker group
    usermod -aG docker openclaw
    
    # Enable and start Docker
    systemctl enable docker
    systemctl start docker
fi

# Verify Docker installation
docker --version
docker compose version

# -----------------------------------------------------------------------------
# Install Tailscale
# -----------------------------------------------------------------------------

log "Installing Tailscale..."
if ! command -v tailscale &> /dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi

# Start Tailscale with auth key
log "Authenticating Tailscale..."
TAILSCALE_ARGS="--auth-key=$TAILSCALE_AUTH_KEY --hostname=$TAILSCALE_HOSTNAME"

if [ -n "$TAILSCALE_ADVERTISE_TAGS" ]; then
    TAILSCALE_ARGS="$TAILSCALE_ARGS --advertise-tags=$TAILSCALE_ADVERTISE_TAGS"
fi

tailscale up $TAILSCALE_ARGS

# Wait for Tailscale to connect
sleep 5
log "Tailscale status:"
tailscale status

# -----------------------------------------------------------------------------
# Clone OpenClaw Repository
# -----------------------------------------------------------------------------

log "Cloning OpenClaw repository..."
cd "$OPENCLAW_DIR"

if [ ! -d "$OPENCLAW_DIR/.git" ]; then
    git clone https://github.com/openclaw/openclaw.git .
else
    git pull origin main
fi

# -----------------------------------------------------------------------------
# Create Environment File
# -----------------------------------------------------------------------------

log "Creating environment file..."
cat > "$OPENCLAW_DIR/.env" << EOF
# OpenClaw Environment Configuration
# Generated by Terraform startup script

# Docker image (must match what we build with 'docker build -t openclaw:local')
OPENCLAW_IMAGE=openclaw:local

# Gateway configuration
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN
OPENCLAW_GATEWAY_BIND=loopback
OPENCLAW_GATEWAY_PORT=$OPENCLAW_GATEWAY_PORT

# Tailscale configuration
OPENCLAW_TAILSCALE_MODE=$TAILSCALE_SERVE_MODE

# State directories
OPENCLAW_CONFIG_DIR=$OPENCLAW_STATE_DIR
OPENCLAW_WORKSPACE_DIR=$OPENCLAW_WORKSPACE_DIR
XDG_CONFIG_HOME=$OPENCLAW_STATE_DIR

# Keyring password for secure storage
GOG_KEYRING_PASSWORD=$(openssl rand -hex 16)

# Model provider credentials
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY

# Messaging channel tokens
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
SLACK_APP_TOKEN=$SLACK_APP_TOKEN
EOF

# Secure the environment file
chmod 600 "$OPENCLAW_DIR/.env"
chown openclaw:openclaw "$OPENCLAW_DIR/.env"

# Also create .env in the state directory for the daemon
cp "$OPENCLAW_DIR/.env" "$OPENCLAW_STATE_DIR/.env"
chmod 600 "$OPENCLAW_STATE_DIR/.env"
chown openclaw:openclaw "$OPENCLAW_STATE_DIR/.env"

# -----------------------------------------------------------------------------
# Create Docker Compose Override
# -----------------------------------------------------------------------------

log "Creating Docker Compose configuration..."
cat > "$OPENCLAW_DIR/docker-compose.override.yml" << 'EOF'
# Docker Compose override for GCP deployment
# This file is merged with the main docker-compose.yml
# IMPORTANT: Use host networking so Tailscale Serve can reach the gateway

services:
  openclaw-gateway:
    network_mode: "host"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
EOF

chown openclaw:openclaw "$OPENCLAW_DIR/docker-compose.override.yml"

# -----------------------------------------------------------------------------
# Create OpenClaw Configuration
# -----------------------------------------------------------------------------

log "Creating OpenClaw configuration..."
cat > "$OPENCLAW_STATE_DIR/openclaw.json" << EOF
{
  "gateway": {
    "mode": "local",
    "bind": "loopback",
    "port": $OPENCLAW_GATEWAY_PORT,
    "controlUi": {
      "enabled": true
    },
    "auth": {
      "mode": "token",
      "token": "$OPENCLAW_GATEWAY_TOKEN",
      "allowTailscale": true
    }
  },
  "agents": {
    "defaults": {
      "model": {
        "primary": "anthropic/claude-opus-4-5"
      },
      "sandbox": {
        "mode": "non-main"
      }
    }
  },
  "channels": {},
  "logging": {
    "redactSensitive": "tools"
  },
  "plugins": {
    "entries": {
      "discord": {
        "enabled": true
      }
    }
  }
}
EOF

# Add password auth if using Funnel
if [ "$TAILSCALE_SERVE_MODE" = "funnel" ] && [ -n "$OPENCLAW_GATEWAY_PASSWORD" ]; then
    # Update config to use password auth for Funnel
    jq '.gateway.auth.mode = "password" | .gateway.auth.password = env.OPENCLAW_GATEWAY_PASSWORD' \
        "$OPENCLAW_STATE_DIR/openclaw.json" > "$OPENCLAW_STATE_DIR/openclaw.json.tmp"
    mv "$OPENCLAW_STATE_DIR/openclaw.json.tmp" "$OPENCLAW_STATE_DIR/openclaw.json"
fi

chmod 600 "$OPENCLAW_STATE_DIR/openclaw.json"
chown openclaw:openclaw "$OPENCLAW_STATE_DIR/openclaw.json"

# -----------------------------------------------------------------------------
# Build and Start OpenClaw
# -----------------------------------------------------------------------------

log "Building OpenClaw Docker image..."
cd "$OPENCLAW_DIR"

# Build the Docker image (the compose file expects openclaw:local to exist)
docker build -t openclaw:local .

log "Starting OpenClaw Gateway..."
# Use explicit -f flags to ensure override is applied (required for host networking)
docker compose -f docker-compose.yml -f docker-compose.override.yml up -d openclaw-gateway

# Wait for the gateway to start
sleep 10

# Check if the gateway is running
if docker compose -f docker-compose.yml -f docker-compose.override.yml ps | grep -q "running"; then
    log "OpenClaw Gateway is running!"
    
    # Wait for gateway to be fully ready
    sleep 15
    
    # Auto-approve any pending device pairing requests
    log "Checking for pending device pairing requests..."
    PENDING=$(docker compose -f docker-compose.yml -f docker-compose.override.yml exec -T openclaw-gateway node /app/openclaw.mjs devices list --json 2>/dev/null | jq -r '.pending[]?.id // empty' 2>/dev/null)
    if [ -n "$PENDING" ]; then
        for REQUEST_ID in $PENDING; do
            log "Auto-approving device request: $REQUEST_ID"
            docker compose -f docker-compose.yml -f docker-compose.override.yml exec -T openclaw-gateway node /app/openclaw.mjs devices approve "$REQUEST_ID" 2>/dev/null || true
        done
    else
        log "No pending device pairing requests."
    fi
else
    log "WARNING: OpenClaw Gateway may not be running. Check logs with:"
    log "docker compose -f $OPENCLAW_DIR/docker-compose.yml -f $OPENCLAW_DIR/docker-compose.override.yml logs"
fi

# -----------------------------------------------------------------------------
# Configure Tailscale Serve
# -----------------------------------------------------------------------------

if [ "$TAILSCALE_SERVE_MODE" != "off" ]; then
    log "Configuring Tailscale $TAILSCALE_SERVE_MODE..."
    
    # Wait for the gateway to be ready
    sleep 5
    
    if [ "$TAILSCALE_SERVE_MODE" = "serve" ]; then
        tailscale serve --bg http://127.0.0.1:$OPENCLAW_GATEWAY_PORT
    elif [ "$TAILSCALE_SERVE_MODE" = "funnel" ]; then
        tailscale funnel --bg http://127.0.0.1:$OPENCLAW_GATEWAY_PORT
    fi
    
    log "Tailscale $TAILSCALE_SERVE_MODE configured. Access via:"
    tailscale status
fi

# -----------------------------------------------------------------------------
# Create Systemd Service for Docker Compose
# -----------------------------------------------------------------------------

log "Creating systemd service..."
cat > /etc/systemd/system/openclaw.service << EOF
[Unit]
Description=OpenClaw Gateway
Requires=docker.service
After=docker.service tailscaled.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$OPENCLAW_DIR
ExecStart=/usr/bin/docker compose -f docker-compose.yml -f docker-compose.override.yml up -d
ExecStop=/usr/bin/docker compose -f docker-compose.yml -f docker-compose.override.yml down
User=openclaw
Group=docker
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable openclaw.service

# -----------------------------------------------------------------------------
# Final Status
# -----------------------------------------------------------------------------

log "=========================================="
log "OpenClaw GCP Deployment Complete!"
log "=========================================="
log ""
log "Tailscale Status:"
tailscale status
log ""
log "Docker Status:"
docker compose -f "$OPENCLAW_DIR/docker-compose.yml" -f "$OPENCLAW_DIR/docker-compose.override.yml" ps
log ""
log "Access Methods:"
log "  1. Via Tailscale: https://$TAILSCALE_HOSTNAME.<your-tailnet>.ts.net/"
log "  2. Via IAP Tunnel: gcloud compute start-iap-tunnel $(hostname) $OPENCLAW_GATEWAY_PORT --local-host-port=localhost:$OPENCLAW_GATEWAY_PORT"
log ""
log "Logs: /var/log/openclaw-startup.log"
log "=========================================="
